development:
  adapter: postgresql
  database: sample
  username: sample
  password: sample
  host: localhost

test:
  adapter: postgresql
  database: sample
  username: sample
  password: sample
  host: localhost

