name: Ruby gem rspec test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.5.x'
          - '2.6.x'
          - '2.7.x'

    steps:
    - name: Checkout current branch
      uses: actions/checkout@v2

    - name: Install sqlite3 on system
        run: |
          sudo apt-get install libsqlite3-dev

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        version: ${{ matrix.ruby }}
    
    - name : Install dependency
      run: |
        bundle install
        
    - name: Run appraisal to install different active records version
      run: |
        bundle exec appraisal
        
    - name: Run rspec test across different active records version
      run: |
        bundle exec appraisal rspec
